import type { GameContext } from "../types/game";
import { wordExistsInSpanishDictionary } from "../services/dictionary/spanishDictionary";

export const LETTERS = "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ".split("");

export const GAME_CONTEXTS: GameContext[] = [
  "Animales",
  "Paises",
  "Ciudades",
  "Tecnologia",
  "Programacion",
  "Libre",
];

export const WORD_BANK: Record<GameContext, string[]> = {
  Animales: [
    // A
    "abeja",
    "abejaruco",
    "abejorro",
    "águila",
    "aguilucho",
    "ajolote",
    "alacran",
    "albatroz",
    "alce",
    "alcotan",
    "aligator",
    "alpaca",
    "ameba",
    "anaconda",
    "anémona",
    "anguila",
    "antilope",
    "araña",
    "ardilla",
    "armiño",
    "armadillo",
    "avestruz",
    "avutarda",
    "axolote",
    // B
    "babuino",
    "ballena",
    "barracuda",
    "bisonte",
    "boa",
    "bonito",
    "bufalo",
    "buho",
    "buitre",
    "burro",
    // C
    "caballo",
    "cabra",
    "caimán",
    "camaleón",
    "camello",
    "canario",
    "canguro",
    "capibara",
    "caracol",
    "carpa",
    "castor",
    "cebra",
    "cerdo",
    "ciervo",
    "cigüeña",
    "cisne",
    "coati",
    "cobra",
    "cocodrilo",
    "cóndor",
    "conejo",
    "cormorán",
    "coyote",
    "cuervo",
    "culebra",
    "cuy",
    // D
    "delfín",
    "dingo",
    "dromedario",
    // E
    "elefante",
    "elefante marino",
    "erizo",
    "escarabajo",
    "escorpion",
    "estrella de mar",
    // F
    "faisán",
    "flamenco",
    "foca",
    "fosa",
    "frailecillo",
    // G
    "gacela",
    "gallina",
    "gallo",
    "gato",
    "gavial",
    "gaviota",
    "gecko",
    "glotón",
    "gorila",
    "grillo",
    "grulla",
    "guacamayo",
    "guepardo",
    "guila",
    "guanaco",
    // H
    "halcón",
    "hamster",
    "hiena",
    "hipocampo",
    "hipopótamo",
    "hormiga",
    "hurón",
    // I
    "ibis",
    "iguana",
    "impala",
    // J
    "jabali",
    "jaguar",
    "jirafa",
    // K
    "koala",
    "kiwi",
    "komodo",
    // L
    "lagarto",
    "lamprea",
    "langosta",
    "lechuza",
    "lemur",
    "leopardo",
    "liebre",
    "lince",
    "llama",
    "lobo",
    "loro",
    "luciérnaga",
    "lutra",
    // M
    "mandril",
    "mangosta",
    "manta raya",
    "mariposa",
    "marmota",
    "medusa",
    "milano",
    "mink",
    "mono",
    "morsa",
    "mosca",
    "mosquito",
    "muflón",
    "murcielago",
    // N
    "narval",
    "nutria",
    // Ñ
    "ñandú",
    "ñu",
    // O
    "okapi",
    "orangutan",
    "orca",
    "orix",
    "ornitorrinco",
    "oso",
    "oso hormiguero",
    "oso panda",
    "oso polar",
    "oveja",
    // P
    "paloma",
    "pantera",
    "pato",
    "pavo",
    "pavo real",
    "pelicano",
    "periquito",
    "perro",
    "pez espada",
    "pez globo",
    "pez payaso",
    "pez volador",
    "pingüino",
    "piton",
    "polilla",
    "puercoespin",
    "pulpo",
    "puma",
    // Q
    "quetzal",
    // R
    "rana",
    "rata",
    "raton",
    "raya",
    "reno",
    "rinoceronte",
    "ruiseñor",
    // S
    "salamandra",
    "salmon",
    "sapo",
    "sardina",
    "serpiente",
    "suricata",
    // T
    "tapir",
    "tejón",
    "tiburon",
    "tigre",
    "topo",
    "tortuga",
    "toucan",
    "toro",
    "trucha",
    // U
    "urogallo",
    "urraca",
    // V
    "vaca",
    "venado",
    "vicuña",
    "visón",
    "víbora",
    "vultur",
    // W
    "walabi",
    "wombat",
    // X
    "xoloitzcuintle",
    // Y
    "yak",
    "yegua",
    // Z
    "zarigüeya",
    "zorro",
    "zorrillo",
    "zurito",
  ],
  Paises: [
    // A
    "afganistan",
    "albania",
    "alemania",
    "andorra",
    "angola",
    "antigua y barbuda",
    "arabia saudi",
    "argelia",
    "argentina",
    "armenia",
    "australia",
    "austria",
    "azerbaiyan",
    // B
    "bahamas",
    "barein",
    "bangladesh",
    "barbados",
    "belgica",
    "belice",
    "benin",
    "bielorrusia",
    "bolivia",
    "bosnia y herzegovina",
    "botswana",
    "brasil",
    "brunei",
    "bulgaria",
    "burkina faso",
    "burundi",
    "butan",
    // C
    "cabo verde",
    "camboya",
    "camerun",
    "canada",
    "catar",
    "chad",
    "chile",
    "china",
    "chipre",
    "colombia",
    "comoras",
    "congo",
    "corea del norte",
    "corea del sur",
    "costa de marfil",
    "costa rica",
    "croacia",
    "cuba",
    // D
    "dinamarca",
    "djibouti",
    "dominica",
    // E
    "ecuador",
    "egipto",
    "el salvador",
    "emiratos arabes unidos",
    "eritrea",
    "eslovaquia",
    "eslovenia",
    "españa",
    "estados unidos",
    "estonia",
    "eswatini",
    "etiopia",
    // F
    "fiji",
    "filipinas",
    "finlandia",
    "francia",
    // G
    "gabon",
    "gambia",
    "georgia",
    "ghana",
    "granada",
    "grecia",
    "guatemala",
    "guinea",
    "guinea ecuatorial",
    "guinea-bisau",
    "guyana",
    // H
    "haiti",
    "honduras",
    "hungria",
    // I
    "india",
    "indonesia",
    "irak",
    "iran",
    "irlanda",
    "islandia",
    "islas marshall",
    "islas salomon",
    "israel",
    "italia",
    // J
    "jamaica",
    "japon",
    "jordania",
    // K
    "kazajistan",
    "kenia",
    "kirguistan",
    "kiribati",
    "kuwait",
    // L
    "laos",
    "lesoto",
    "letonia",
    "libano",
    "liberia",
    "libia",
    "liechtenstein",
    "lituania",
    "luxemburgo",
    // M
    "madagascar",
    "malasia",
    "malawi",
    "maldivas",
    "mali",
    "malta",
    "marruecos",
    "mauricio",
    "mauritania",
    "mexico",
    "micronesia",
    "moldavia",
    "monaco",
    "mongolia",
    "montenegro",
    "mozambique",
    "myanmar",
    // N
    "namibia",
    "nauru",
    "nepal",
    "nicaragua",
    "niger",
    "nigeria",
    "noruega",
    "nueva zelanda",
    // O
    "oman",
    // P
    "pakistan",
    "palaos",
    "panama",
    "papua nueva guinea",
    "paraguay",
    "peru",
    "polonia",
    "portugal",
    // Q
    "qatar",
    // R
    "reino unido",
    "republica centroafricana",
    "republica checa",
    "republica democratica del congo",
    "republica dominicana",
    "rumania",
    "rusia",
    "ruanda",
    // S
    "saint kitts y nevis",
    "samoa",
    "san marino",
    "san vicente y las granadinas",
    "santa lucia",
    "santo tome y principe",
    "senegal",
    "serbia",
    "seychelles",
    "sierra leona",
    "singapur",
    "siria",
    "somalia",
    "sri lanka",
    "sudafrica",
    "sudan",
    "sudan del sur",
    "suecia",
    "suiza",
    "surinam",
    // T
    "tailandia",
    "tanzania",
    "tayikistan",
    "timor oriental",
    "togo",
    "tonga",
    "trinidad y tobago",
    "tunez",
    "turkmenistan",
    "turquia",
    "tuvalu",
    // U
    "ucrania",
    "uganda",
    "uruguay",
    "uzbekistan",
    // V
    "vanuatu",
    "vaticano",
    "venezuela",
    "vietnam",
    // Y
    "yemen",
    // Z
    "zambia",
    "zimbabue",
  ],
  Ciudades: [
    // A
    "abuya",
    "accra",
    "addis abeba",
    "adelaida",
    "agra",
    "ahmedabad",
    "almaty",
    "amman",
    "amsterdam",
    "ankara",
    "antananarivo",
    "antigua guatemala",
    "apia",
    "asmara",
    "astana",
    "asuncion",
    "atenas",
    "auckland",
    // B
    "bagdad",
    "baku",
    "baltimore",
    "bamako",
    "bangkok",
    "bangui",
    "barcelona",
    "barranquilla",
    "beirut",
    "belgrado",
    "berlin",
    "berna",
    "bilbao",
    "bishkek",
    "bogota",
    "brasilia",
    "bratislava",
    "brazzaville",
    "brisbane",
    "bruselas",
    "bucarest",
    "budapest",
    "buenas aires",
    "bujumbura",
    // C
    "cairo",
    "calcuta",
    "calgary",
    "cali",
    "cambridge",
    "canton",
    "cape town",
    "caracas",
    "cartagena",
    "casablanca",
    "chicago",
    "chengdu",
    "chennai",
    "chongqing",
    "ciudad de guatemala",
    "ciudad de mexico",
    "ciudad de panama",
    "colombo",
    "conakri",
    "copenhague",
    "cracovia",
    "curitiba",
    // D
    "dakar",
    "damasco",
    "dar es salaam",
    "delhi",
    "denver",
    "dhaka",
    "doha",
    "dubai",
    "dublin",
    "dusanbe",
    // E
    "edinburgo",
    "estambul",
    "estocolmo",
    // F
    "florencia",
    "fran fort",
    "freetown",
    "fukuoka",
    // G
    "ginebra",
    "glasgow",
    "granada",
    "guadalajara",
    "guangzhou",
    "guatemala",
    // H
    "hamburgo",
    "hanoi",
    "harare",
    "havana",
    "helsinki",
    "hiroshima",
    "ho chi minh",
    "hong kong",
    "honolulu",
    "houston",
    "hyderabad",
    // I
    "ibague",
    "islamabad",
    "istanbul",
    // J
    "jacarta",
    "jartum",
    "jerusalen",
    "johannesburgo",
    // K
    "kabul",
    "kampala",
    "karachi",
    "katmandu",
    "kigali",
    "kingston",
    "kinshasa",
    "kioto",
    "kuala lumpur",
    "kuwait",
    // L
    "lagos",
    "lahore",
    "la habana",
    "la paz",
    "libreville",
    "lima",
    "lisboa",
    "liubliana",
    "lome",
    "londonderry",
    "londres",
    "los angeles",
    "luanda",
    "lusaka",
    // M
    "madrid",
    "male",
    "managua",
    "manama",
    "manila",
    "maputo",
    "marseille",
    "maseru",
    "mbabane",
    "medelin",
    "melbourne",
    "mexico",
    "miami",
    "milan",
    "minneapolis",
    "minsk",
    "mogadiscio",
    "monaco",
    "montevideo",
    "montreal",
    "moscu",
    "mumbai",
    "muscat",
    // N
    "nairobi",
    "napoles",
    "nassau",
    "niamey",
    "nicosia",
    "nueva delhi",
    "nueva york",
    "nueva zelanda",
    // O
    "oslo",
    "ottawa",
    "ouagadougou",
    // P
    "paris",
    "pekin",
    "phnom penh",
    "portland",
    "porto alegre",
    "praga",
    "pretoria",
    "puerto principe",
    "pyongyang",
    // Q
    "quito",
    // R
    "rabat",
    "recife",
    "reikiavik",
    "rio de janeiro",
    "riyadh",
    "roma",
    "rotterdam",
    // S
    "san francisco",
    "san jose",
    "san pablo",
    "san petersburgo",
    "san salvador",
    "santiago",
    "santo domingo",
    "sarajevo",
    "seattle",
    "seul",
    "sevilla",
    "shanghai",
    "shenzhen",
    "singapur",
    "skopie",
    "sofia",
    "suva",
    "sydney",
    // T
    "taipei",
    "tallin",
    "taskent",
    "tegucigalpa",
    "teheran",
    "tel aviv",
    "tiflis",
    "tirana",
    "tokio",
    "toronto",
    "tripoli",
    "tunez",
    // U
    "ulan bator",
    "utrecht",
    // V
    "vaduz",
    "valencia",
    "varsovia",
    "venecia",
    "viena",
    "vientiane",
    "vilna",
    // W
    "washington",
    "wellington",
    "windhoek",
    // X
    "xalapa",
    "xian",
    // Y
    "yamena",
    "yaounde",
    "yerevan",
    "yopal",
    // Z
    "Zagreb",
    "zurich",
  ],
  Tecnologia: [
    "api",
    "backend",
    "cache",
    "docker",
    "endpoint",
    "firebase",
    "git",
    "hosting",
    "internet",
    "javascript",
    "kernel",
    "linux",
    "mongodb",
    "node",
    "oracle",
    "postgres",
    "query",
    "react",
    "supabase",
    "typescript",
    "ubuntu",
    "vite",
    "websocket",
    "xml",
    "yaml",
    "zustand",
  ],
  Programacion: [
    "algoritmo",
    "bucle",
    "compilador",
    "debug",
    "evento",
    "funcion",
    "git",
    "hook",
    "interface",
    "json",
    "lambda",
    "modulo",
    "namespace",
    "objeto",
    "promesa",
    "query",
    "recursion",
    "script",
    "tipado",
    "variable",
  ],
  Libre: [],
};

export function normalizeWord(value: string) {
  return value
    .trim()
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}

export function getAvailableLetters(context: GameContext): string[] {
  if (context === "Libre") return [...LETTERS];
  const words = CATEGORY_WORD_SETS[context];
  if (!words || words.size === 0) return [...LETTERS];
  return LETTERS.filter((letter) => {
    const normalizedLetter = normalizeWord(letter);
    return Array.from(words).some((word) =>
      word.startsWith(normalizedLetter),
    );
  });
}

const LOCAL_WORD_SET = new Set(
  Object.values(WORD_BANK).flat().map(normalizeWord),
);
const CATEGORY_WORD_SETS = Object.fromEntries(
  Object.entries(WORD_BANK).map(([context, words]) => [
    context,
    new Set(words.map(normalizeWord)),
  ]),
) as Record<GameContext, Set<string>>;

export async function validateWord(
  word: string,
  letter: string,
  context: GameContext,
  usedWords: string[],
) {
  const normalized = normalizeWord(word);
  const expectedLetter = normalizeWord(letter);

  if (!normalized) return { isValid: false, reason: "Escribe una palabra." };
  if (usedWords.includes(normalized))
    return { isValid: false, reason: "Palabra repetida." };
  if (!normalized.startsWith(expectedLetter)) {
    return { isValid: false, reason: `Debe iniciar con ${letter}.` };
  }

  if (context !== "Libre") {
    const categoryWords = CATEGORY_WORD_SETS[context];

    if (!categoryWords.has(normalized)) {
      return { isValid: false, reason: `No pertenece a ${context}.` };
    }

    return { isValid: true, reason: `+10 puntos · ${context} OK` };
  }

  if (LOCAL_WORD_SET.has(normalized))
    return { isValid: true, reason: "+10 puntos · Banco local OK" };

  if (!(await wordExistsInSpanishDictionary(normalized))) {
    return { isValid: false, reason: "No aparece en el diccionario." };
  }

  return { isValid: true, reason: "+10 puntos · Diccionario OK" };
}
